### Recuperar todas las películas
GET http://localhost:3000/wishlist

### Recuperar una película por id
GET http://localhost:3000/wishlist/Celular

### Recuperar todas las películas por un género
GET http://localhost:3000/wishlist?min=400&max=600

### Crear una película con POST
POST http://localhost:3000/wishlist
Content-Type: application/json

{
  "title": "Audífonos",
  "precio": 29,
  "descripcion": "Auriculares",
  "type": ["Health"]
}

### Borrar una película
DELETE http://localhost:1234/wishlist/Celular

### Actualizar una película
PATCH http://localhost:3000/wishlist/Celular
Content-Type: application/json

{
  "precio": 400
}